# -*- coding: utf-8 -*-
"""const.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xuf8MIwhhGgcWDLg4Kdt333YZkSuWTUP
"""

#define constant values for project-wide use 
vocabularyArr = [ "up", "down", "rotatel", "rotater", "pitchl", "pitchr", "pitchf", "pitchb" ] #lower case only
vocabularyDict = generateDictionary(vocabularyArr) #redundant, for convenience only

#define word-integer mapping and related helpers

def generateDictionary(lst):
  retDict = {}
  for i in range(0, len(lst)):
    retDict[lst[i]] = i
  print(retDict)
  return retDict

def toInteger(str):
  if str.lower() in vocabularyDict:
    return vocabularyDict.get(str)
  else:
    return -1

def toWord(int):
  if int < len(vocabularyArr):
    return vocabularyArr[int]
  else:
    return "n/f"

#print(toWord(5))

